version: '3'
services:
  mysql:
    image: 'mysql:5.7.10'
    container_name: streaming-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'

  api:
    build: .
    depends_on:
      - mysql
    container_name: streaming-api
    ports:
      - 3333:3333
    volumes:
      - ./usr:/app
